name: 'Proselint'
description: 'Run proselint on markdown files'
inputs:
  files:
    description: 'Glob pattern for markdown files'
    required: false
    default: '**/*.md'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install proselint
      run: pip install proselint
      shell: bash

    - name: Run proselint
      run: |
        shopt -s globstar nullglob
        for md in ${{ inputs.files }}; do
          echo "Linting $md"
          proselint "$md"
        done
      shell: bash
