name: 'Lint Markdown'
on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint markdown with Proselint
        uses: ./.github/actions/proselint
        with:
          files: '**/*.md'
