name: ShellCheck

on:
  push:
    paths:
      - '**/*.sh'
  pull_request:
    paths:
      - '**/*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ShellCheck and run
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          shellcheck **/*.sh
